<?php

namespace Database\Seeders;

use App\Models\MegaCorporation;
use App\Models\ShipType;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ShipTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ships = [
            // Stellar Dynamics
            [
                'name' => 'Sparrow',
                'description' => 'A nimble scout vessel designed for fast reconnaissance and evasive maneuvers, ideal for mapping and initial scans.',
                'size' => 'Small',
                'weapon_slots' => 1,
                'defense_slots' => 1,
                'utility_slots' => 1,
                'mega_corporation_id' => MegaCorporation::where('name', 'Stellar Dynamics')->first()->id,
            ],
            [
                'name' => 'Hawk',
                'description' => 'A versatile frigate designed for fast transport and secure delivery of valuable goods, popular among traders and smugglers.',
                'size' => 'Medium',
                'weapon_slots' => 2,
                'defense_slots' => 2,
                'utility_slots' => 2,
                'mega_corporation_id' => MegaCorporation::where('name', 'Stellar Dynamics')->first()->id,
            ],
            [
                'name' => 'Peregrine',
                'description' => 'A high-mobility cruiser for combat support, capable of rapid redeployment and providing cover for larger ships.',
                'size' => 'Large',
                'weapon_slots' => 2,
                'defense_slots' => 2,
                'utility_slots' => 2,
                'mega_corporation_id' => MegaCorporation::where('name', 'Stellar Dynamics')->first()->id,
            ],
            [
                'name' => 'Phoenix',
                'description' => 'A fast freighter designed for swift cargo transport, able to move through dangerous regions with ease due to its high agility and defensive options.',
                'size' => 'Large',
                'weapon_slots' => 1,
                'defense_slots' => 2,
                'utility_slots' => 3,
                'mega_corporation_id' => MegaCorporation::where('name', 'Stellar Dynamics')->first()->id,
            ],
            [
                'name' => 'Zephyr',
                'description' => 'A specialized exploration vessel that deploys drones and shuttles for deep-space missions, allowing it to survey planets and anomalies.',
                'size' => 'Extra Large',
                'weapon_slots' => 2,
                'defense_slots' => 2,
                'utility_slots' => 3,
                'mega_corporation_id' => MegaCorporation::where('name', 'Stellar Dynamics')->first()->id,
            ],
            [
                'name' => 'Eclipse',
                'description' => 'A high-tech stealth battleship equipped with cutting-edge cloaking systems, built for rapid strikes and covert operations.',
                'size' => 'Capital',
                'weapon_slots' => 3,
                'defense_slots' => 3,
                'utility_slots' => 2,
                'mega_corporation_id' => MegaCorporation::where('name', 'Stellar Dynamics')->first()->id,
            ],
            // Galactic Federation Shipyards
            [
                'name' => 'Guardian',
                'description' => 'A swift and agile patrol ship designed for rapid deployment, ideal for monitoring and securing Federation borders.',
                'size' => 'Small',
                'weapon_slots' => 2,
                'defense_slots' => 1,
                'utility_slots' => 1,
                'mega_corporation_id' => MegaCorporation::where('name', 'Galactic Federation Shipyards')->first()->id,
            ],
            [
                'name' => 'Sentinel',
                'description' => 'The Federation’s dependable frigate, versatile for both convoy escort and frontline defense, favored for its durability.',
                'size' => 'Medium',
                'weapon_slots' => 3,
                'defense_slots' => 2,
                'utility_slots' => 1,
                'mega_corporation_id' => MegaCorporation::where('name', 'Galactic Federation Shipyards')->first()->id,
            ],
            [
                'name' => 'Aegis',
                'description' => 'A heavy combat cruiser built to withstand long engagements, prioritizing armor and firepower for Federation defense.',
                'size' => 'Large',
                'weapon_slots' => 3,
                'defense_slots' => 2,
                'utility_slots' => 2,
                'mega_corporation_id' => MegaCorporation::where('name', 'Galactic Federation Shipyards')->first()->id,
            ],
            [
                'name' => 'Providence',
                'description' => 'A high-capacity freighter essential to Federation trade, built to transport large volumes of goods across controlled space.',
                'size' => 'Large',
                'weapon_slots' => 1,
                'defense_slots' => 2,
                'utility_slots' => 3,
                'mega_corporation_id' => MegaCorporation::where('name', 'Galactic Federation Shipyards')->first()->id,
            ],
            [
                'name' => 'Atlas',
                'description' => 'Designed for fleet support, the "Atlas" deploys drones and repair modules, enhancing nearby ships’ operational capabilities.',
                'size' => 'Extra Large',
                'weapon_slots' => 2,
                'defense_slots' => 2,
                'utility_slots' => 3,
                'mega_corporation_id' => MegaCorporation::where('name', 'Galactic Federation Shipyards')->first()->id,
            ],
            [
                'name' => 'Titan',
                'description' => 'The ultimate Federation warship, the "Titan" is a dreadnought built for large-scale battles and unmatched system security.',
                'size' => 'Capital',
                'weapon_slots' => 4,
                'defense_slots' => 3,
                'utility_slots' => 2,
                'mega_corporation_id' => MegaCorporation::where('name', 'Galactic Federation Shipyards')->first()->id,
            ],
            // Astral Heavy Industries
            [
                'name' => 'Leviathan',
                'description' => 'A massive freighter capable of carrying vast amounts of cargo, fortified with reinforced armor to withstand long journeys and potential hazards.',
                'size' => 'Large',
                'weapon_slots' => 1,
                'defense_slots' => 3,
                'utility_slots' => 3,
                'mega_corporation_id' => MegaCorporation::where('name', 'Astral Heavy Industries')->first()->id,
            ],
            [
                'name' => 'Goliath',
                'description' => 'A destroyer-class vessel built for direct assault, equipped with heavy weaponry and thick armor to engage in prolonged battles.',
                'size' => 'Medium',
                'weapon_slots' => 3,
                'defense_slots' => 2,
                'utility_slots' => 1,
                'mega_corporation_id' => MegaCorporation::where('name', 'Astral Heavy Industries')->first()->id,
            ],
            [
                'name' => 'Behemoth',
                'description' => 'A specialized ship for asteroid mining, equipped with industrial-grade mining lasers and ample cargo space for extracted resources.',
                'size' => 'Large',
                'weapon_slots' => 1, // Mining Laser
                'defense_slots' => 2,
                'utility_slots' => 2,
                'mega_corporation_id' => MegaCorporation::where('name', 'Astral Heavy Industries')->first()->id,
            ],
            [
                'name' => 'Bastion',
                'description' => 'A durable cruiser designed for fleet defense, equipped with powerful shields and defensive systems to protect allied ships.',
                'size' => 'Large',
                'weapon_slots' => 2,
                'defense_slots' => 3,
                'utility_slots' => 2,
                'mega_corporation_id' => MegaCorporation::where('name', 'Astral Heavy Industries')->first()->id,
            ],
            [
                'name' => 'Colossus',
                'description' => 'A colossal battleship equipped with overwhelming firepower and layered armor, serving as the spearhead of any combat fleet.',
                'size' => 'Capital',
                'weapon_slots' => 4,
                'defense_slots' => 4,
                'utility_slots' => 2,
                'mega_corporation_id' => MegaCorporation::where('name', 'Astral Heavy Industries')->first()->id,
            ],
            [
                'name' => 'Fortress',
                'description' => 'A unique, semi-stationary vessel optimized for creating defensive perimeters, equipped with advanced shielding and support for nearby allied units.',
                'size' => 'Extra Large',
                'weapon_slots' => 2,
                'defense_slots' => 2,
                'utility_slots' => 3,
                'mega_corporation_id' => MegaCorporation::where('name', 'Astral Heavy Industries')->first()->id,
            ],

            // Peregrine Robotics
            [
                'name' => 'Wraith',
                'description' => 'A stealthy frigate equipped with advanced sensors and cloaking technology, designed for quick reconnaissance and covert operations.',
                'size' => 'Small',
                'weapon_slots' => 1,
                'defense_slots' => 1,
                'utility_slots' => 2,
                'mega_corporation_id' => MegaCorporation::where('name', 'Peregrine Robotics')->first()->id,
            ],
            [
                'name' => 'Shadow',
                'description' => 'A fast and lightweight vessel optimized for scouting and long-range exploration with advanced navigation and sensor systems.',
                'size' => 'Small',
                'weapon_slots' => 1,
                'defense_slots' => 1,
                'utility_slots' => 2,
                'mega_corporation_id' => MegaCorporation::where('name', 'Peregrine Robotics')->first()->id,
            ],
            [
                'name' => 'Vanguard',
                'description' => 'A versatile corvette with modular options for support and defense, ideal for escorting larger vessels and patrolling.',
                'size' => 'Medium',
                'weapon_slots' => 2,
                'defense_slots' => 2,
                'utility_slots' => 1,
                'mega_corporation_id' => MegaCorporation::where('name', 'Peregrine Robotics')->first()->id,
            ],
            [
                'name' => 'Specter',
                'description' => 'A specialized frigate for electronic warfare, equipped with systems to disrupt enemy communications and targeting.',
                'size' => 'Small',
                'weapon_slots' => 1,
                'defense_slots' => 1,
                'utility_slots' => 2,
                'mega_corporation_id' => MegaCorporation::where('name', 'Peregrine Robotics')->first()->id,
            ],
            [
                'name' => 'Swift',
                'description' => 'An agile interceptor built for high-speed engagements and interception of smaller enemy vessels, prioritizing speed over armor.',
                'size' => 'Small',
                'weapon_slots' => 2,
                'defense_slots' => 1,
                'utility_slots' => 1,
                'mega_corporation_id' => MegaCorporation::where('name', 'Peregrine Robotics')->first()->id,
            ],
            [
                'name' => 'Aquila',
                'description' => 'A stealth cruiser equipped with high-grade cloaking and advanced sensors, perfect for covert missions and reconnaissance in hostile territories.',
                'size' => 'Medium',
                'weapon_slots' => 2,
                'defense_slots' => 2,
                'utility_slots' => 2,
                'mega_corporation_id' => MegaCorporation::where('name', 'Peregrine Robotics')->first()->id,
            ],
            [
                'name' => 'Raven',
                'description' => 'A drone carrier capable of launching and controlling multiple combat drones, ideal for surveillance and support.',
                'size' => 'Large',
                'weapon_slots' => 1,
                'defense_slots' => 2,
                'utility_slots' => 3,
                'mega_corporation_id' => MegaCorporation::where('name', 'Peregrine Robotics')->first()->id,
            ],
            [
                'name' => 'Nebula',
                'description' => 'A cruiser built for deep-space exploration, equipped with cutting-edge navigation and scanning technology to venture into unknown regions.',
                'size' => 'Medium',
                'weapon_slots' => 1,
                'defense_slots' => 2,
                'utility_slots' => 3,
                'mega_corporation_id' => MegaCorporation::where('name', 'Peregrine Robotics')->first()->id,
            ],

            // Orion Shipbuilders
            [
                'name' => 'Atlas Heavy Freighter',
                'description' => 'A large and robust freighter designed to transport substantial cargo loads safely across the galaxy.',
                'size' => 'Large',
                'weapon_slots' => 2,
                'defense_slots' => 3,
                'utility_slots' => 4,
                'mega_corporation_id' => MegaCorporation::where('name', 'Orion Shipbuilders')->first()->id,
            ],
            [
                'name' => 'Titan Mining Barge',
                'description' => 'A heavily equipped mining vessel with reinforced structure and optimized for resource extraction in hazardous environments.',
                'size' => 'Large',
                'weapon_slots' => 1,
                'defense_slots' => 2,
                'utility_slots' => 4,
                'mega_corporation_id' => MegaCorporation::where('name', 'Orion Shipbuilders')->first()->id,
            ],
            [
                'name' => 'Bulwark Assault Frigate',
                'description' => 'A highly fortified frigate suited for frontline assaults and defense, providing both firepower and durability.',
                'size' => 'Medium',
                'weapon_slots' => 2,
                'defense_slots' => 3,
                'utility_slots' => 1,
                'mega_corporation_id' => MegaCorporation::where('name', 'Orion Shipbuilders')->first()->id,
            ],
            [
                'name' => 'Fortress Battlecruiser',
                'description' => 'A heavily armored cruiser with enhanced defense capabilities, designed to hold the line and protect allies in combat zones.',
                'size' => 'Large',
                'weapon_slots' => 3,
                'defense_slots' => 4,
                'utility_slots' => 2,
                'mega_corporation_id' => MegaCorporation::where('name', 'Orion Shipbuilders')->first()->id,
            ],
            [
                'name' => 'Aegis Patrol Cutter',
                'description' => 'A patrol vessel designed for quick response and area control, with sufficient firepower to handle most threats in patrolled sectors.',
                'size' => 'Medium',
                'weapon_slots' => 2,
                'defense_slots' => 2,
                'utility_slots' => 1,
                'mega_corporation_id' => MegaCorporation::where('name', 'Orion Shipbuilders')->first()->id,
            ],
            [
                'name' => 'Goliath Heavy Hauler',
                'description' => 'A massive cargo hauler for transporting large amounts of goods, fitted with reinforced hulls and additional defense mechanisms for secure delivery.',
                'size' => 'Extra-Large',
                'weapon_slots' => 2,
                'defense_slots' => 4,
                'utility_slots' => 5,
                'mega_corporation_id' => MegaCorporation::where('name', 'Orion Shipbuilders')->first()->id,
            ],
            [
                'name' => 'Sentinel Defense Cruiser',
                'description' => 'A defensive cruiser designed to provide close support and protection to larger vessels or installations in combat zones.',
                'size' => 'Large',
                'weapon_slots' => 3,
                'defense_slots' => 3,
                'utility_slots' => 2,
                'mega_corporation_id' => MegaCorporation::where('name', 'Orion Shipbuilders')->first()->id,
            ],
            [
                'name' => 'Endurance Exploration Vessel',
                'description' => 'Built for deep-space exploration and endurance, with robust defenses and ample space for scientific equipment and crew accommodations.',
                'size' => 'Large',
                'weapon_slots' => 2,
                'defense_slots' => 3,
                'utility_slots' => 3,
                'mega_corporation_id' => MegaCorporation::where('name', 'Orion Shipbuilders')->first()->id,
            ],

            // Hammerhead Industries
            [
                'name' => 'Anvil Heavy Destroyer',
                'description' => 'A powerful, front-line destroyer, designed for engaging and breaking through enemy lines with high-damage output and reinforced armor.',
                'size' => 'Large',
                'weapon_slots' => 3,
                'defense_slots' => 2,
                'utility_slots' => 1,
                'mega_corporation_id' => MegaCorporation::where('name', 'Hammerhead Industries')->first()->id,
            ],
            [
                'name' => 'Mauler Assault Frigate',
                'description' => 'A mid-sized, highly maneuverable frigate, built for fast assault missions with a strong offensive capability and moderate defense.',
                'size' => 'Medium',
                'weapon_slots' => 2,
                'defense_slots' => 2,
                'utility_slots' => 1,
                'mega_corporation_id' => MegaCorporation::where('name', 'Hammerhead Industries')->first()->id,
            ],
            [
                'name' => 'Juggernaut Super-Heavy Cruiser',
                'description' => 'The pride of Hammerhead’s lineup, a heavily armed and armored cruiser designed to lead battles with its immense firepower and resilience.',
                'size' => 'Extra-Large',
                'weapon_slots' => 6,
                'defense_slots' => 5,
                'utility_slots' => 2,
                'mega_corporation_id' => MegaCorporation::where('name', 'Hammerhead Industries')->first()->id,
            ],
            [
                'name' => 'Grizzly Tactical Gunship',
                'description' => 'A gunship designed for tactical strikes and close-quarters support, with balanced weaponry and sturdy armor.',
                'size' => 'Medium',
                'weapon_slots' => 3,
                'defense_slots' => 2,
                'utility_slots' => 1,
                'mega_corporation_id' => MegaCorporation::where('name', 'Hammerhead Industries')->first()->id,
            ],
            [
                'name' => 'Colossus Siege Carrier',
                'description' => 'A large carrier capable of launching support drones and smaller vessels, built to endure siege operations with enhanced defensive slots.',
                'size' => 'Extra-Large',
                'weapon_slots' => 4,
                'defense_slots' => 4,
                'utility_slots' => 4,
                'mega_corporation_id' => MegaCorporation::where('name', 'Hammerhead Industries')->first()->id,
            ],
            [
                'name' => 'Bulldozer Industrial Freighter',
                'description' => 'A heavily armored freighter, optimized for transporting high-value cargo through dangerous territories.',
                'size' => 'Large',
                'weapon_slots' => 1,
                'defense_slots' => 3,
                'utility_slots' => 3,
                'mega_corporation_id' => MegaCorporation::where('name', 'Hammerhead Industries')->first()->id,
            ],
            [
                'name' => 'Golem Mobile Refinery',
                'description' => 'An industrial ship designed for resource refinement on-the-go, outfitted with processing modules and enhanced defenses.',
                'size' => 'Large',
                'weapon_slots' => 1,
                'defense_slots' => 3,
                'utility_slots' => 4,
                'mega_corporation_id' => MegaCorporation::where('name', 'Hammerhead Industries')->first()->id,
            ],
            [
                'name' => 'Rhino Heavy Escort',
                'description' => 'A heavily armored escort ship designed to protect vulnerable ships or assets in hostile zones with reliable defensive and offensive capabilities.',
                'size' => 'Large',
                'weapon_slots' => 3,
                'defense_slots' => 3,
                'utility_slots' => 1,
                'mega_corporation_id' => MegaCorporation::where('name', 'Hammerhead Industries')->first()->id,
            ],

            // Nova Transport Corp.
            [
                'name' => 'Swiftwind Light Cargo Runner',
                'description' => 'A high-speed cargo runner designed for transporting valuable goods through both peaceful and contested space. The Swiftwind is favored for its quick acceleration and ease of maneuvering.',
                'size' => 'Small',
                'weapon_slots' => 1,
                'defense_slots' => 1,
                'utility_slots' => 2,
                'mega_corporation_id' => MegaCorporation::where('name', 'Nova Transport Corp.')->first()->id,
            ],
            [
                'name' => 'Falconer Secure Transport',
                'description' => 'A specialized secure transport vessel outfitted for high-value cargo protection. The Falconer includes reinforced armor and multiple layers of defense, making it ideal for transporting sensitive cargo through potentially hostile regions.',
                'size' => 'Medium',
                'weapon_slots' => 2,
                'defense_slots' => 2,
                'utility_slots' => 2,
                'mega_corporation_id' => MegaCorporation::where('name', 'Nova Transport Corp.')->first()->id,
            ],
            [
                'name' => 'Starfire Fast Freighter',
                'description' => 'Built for rapid long-distance hauling, the Starfire is optimized for swift transit along Syndicate routes. It is designed with a focus on high cargo capacity and speed, sacrificing some defensive capabilities for increased transport efficiency.',
                'size' => 'Large',
                'weapon_slots' => 2,
                'defense_slots' => 1,
                'utility_slots' => 3,
                'mega_corporation_id' => MegaCorporation::where('name', 'Nova Transport Corp.')->first()->id,
            ],
            [
                'name' => 'Peregrine Blockade Runner',
                'description' => 'A specialized vessel designed to break through enemy lines and hostile zones, the Peregrine is equipped with advanced evasion and speed capabilities. Its stealthy, durable design makes it ideal for smuggling or bypassing blockades.',
                'size' => 'Medium',
                'weapon_slots' => 2,
                'defense_slots' => 2,
                'utility_slots' => 2,
                'mega_corporation_id' => MegaCorporation::where('name', 'Nova Transport Corp.')->first()->id,
            ],
            [
                'name' => 'Vanguard Heavy Transport',
                'description' => 'Nova’s heavy-lift transport designed for maximum security and transport capacity. The Vanguard’s reinforced hull and secure compartments make it perfect for high-stakes, high-value trade routes within Syndicate space.',
                'size' => 'Large',
                'weapon_slots' => 2,
                'defense_slots' => 2,
                'utility_slots' => 3,
                'mega_corporation_id' => MegaCorporation::where('name', 'Nova Transport Corp.')->first()->id,
            ],
        ];

        foreach ($ships as $ship) {
            ShipType::create($ship);
        }
    }
}
